application: dcappstore
version: 1-3-dev
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /vote
  script: vote.py

- url: /vote/feed
  script: vote.py

- url: /form
  script: form.py

- url: /submit
  script: form.py

- url: /dynamic/image
  script: dynamic/image.py

- url: /admin/static
  static_dir: admin/static
  login: admin

- url: /admin/imageUpload
  script: admin/imageUpload.py
  login: admin

- url: .*
  script: main.py
 

  